#!/bin/bash -x

#
# GLOBAL VARIABLES
#

ACCESS_TOKEN="2296783.pt._hMMcblHJJnRc9W1IscXBQTV5YZubZl0LtAZ7Wd8LBjywW-zr5nigXW0Ev3BGrhBNBfxRqHioAccH7Rn8LwtnA"

ACCOUNT_ID="1283044"

BASE_DIRECTORY=$(dirname "$0")

CURRENT_PROJECT_FILE="$BASE_DIRECTORY/.current-project"

CURRENT_TASK_FILE="$BASE_DIRECTORY/.current-task"

#
# FUNCTIONS
#

function get() {
    curl --silent "$1" \
      -H "Authorization: Bearer $ACCESS_TOKEN" \
      -H "Harvest-Account-Id: $ACCOUNT_ID" \
      -H "User-Agent: Test App (therealsebshady@googlemail.com)"
}

function post() {
    curl --verbose "$1" \
      -H "Authorization: Bearer $ACCESS_TOKEN" \
      -H "Harvest-Account-Id: $ACCOUNT_ID" \
      -H "User-Agent: Test App (therealsebshady@googlemail.com)" \
      -X POST \
      -H "Content-Type: application/json" \
      -d "$2"
}

function start_timing() {
    CURRENT_PROJECT=$(get_current_project)
    CURRENT_TASK=$(get_current_task)
    DATE=$(date +%F)

    DATA=$(cat <<JSON
    "project_id": $CURRENT_PROJECT,
    "task_id": $CURRENT_TASK,
    "spent_date": "$DATE",
    "notes":"$1"
JSON
)

    if [[ ! -z $2 ]]; then
        DATA=$(cat <<JSON
    $DATA,
    "external_reference": {
        "permalink": "$2"
    }
JSON
)
    fi

    post "https://api.harvestapp.com/v2/time_entries" "{$DATA}" | jq '.'
}

function list_projects() {
    get "https://api.harvestapp.com/v2/projects" | \
        jq --raw-output '.projects[] | (.id | tostring) + " " + .name'
}

function list_tasks() {
    get "https://api.harvestapp.com/v2/tasks" | \
        jq --raw-output '.tasks[] | (.id | tostring) + " " + .name'
}

function get_current_user() {
    get "https://api.harvestapp.com/v2/users/me"
}

function get_current_project() {
    if [[ -f "$CURRENT_PROJECT_FILE" ]]; then
        cat "$CURRENT_PROJECT_FILE"
    fi
}

function set_current_project() {
    echo "$1" > "$CURRENT_PROJECT_FILE"
}

function get_current_task() {
    if [[ -f "$CURRENT_TASK_FILE" ]]; then
        cat "$CURRENT_TASK_FILE"
    fi
}

function set_current_task() {
    echo "$1" > "$CURRENT_TASK_FILE"
}

#
# SCRIPT
#

if [[ $# -eq 0 ]]; then
    printf "Usage: %s COMMAND [OPTIONS].\n\n" "$0"
    printf "Availble Commands:\n\n"
    printf "lp\t\tList available projects.\n"
    printf "lt\t\tList available tasks.\n"
    printf "gcp\t\tGet the ID of the current project.\n"
    printf "scp PROJECT_ID\tSet the current project to PROJECT_ID.\n"
    printf "gct\t\tGet the ID of the current task.\n"
    printf "sct TASK_ID\tSet the current task to TASK_ID.\n" exit 1
    printf "st  NOTES [URL]\tStart a new timer on the current project and\n"
    printf "\t\tcurrent task with NOTES and optionally linked to [URL].\n" 
    exit 1
fi

case $1 in
    "lp" )
        list_projects
        ;;
    "lt" )
        list_tasks
        ;;

    "gcp" )
        get_current_project
        ;;

    "scp" )
        set_current_project "$2"
        ;;

    "gct" )
        get_current_task
        ;;

    "sct" )
        set_current_task "$2"
        ;;

    "st" )
        start_timing "$2" "$3"
        ;;
esac
