#!/bin/bash

# https://stackoverflow.com/questions/47050589/create-url-friendly-slug-with-pure-bash/49035906#49035906
function slugify () {
    echo "$1" | \
        iconv -t ascii//TRANSLIT | \
        sed -r s/[~\^]+//g | \
        sed -r s/[^a-zA-Z0-9]+/-/g | \
        sed -r s/^-+\|-+$//g | \
        tr A-Z a-z
}

temp=$(mktemp)

${EDITOR:-vim} "$temp"

title=$(sed -n -e '1p' "$temp")

description=$(sed -n -e '2,$p' "$temp")

issue_json=$(gitlab new-issue "$title" "$description")

echo "Created issue '$(echo "$issue_json" | jq -r '.title')'"

issue_number=$(echo "$issue_json" | jq -r '.references.short')

branch_name=$(slugify "$issue_number-$title")

branch_json=$(gitlab new-branch "$branch_name" "develop")

echo "Created branch '$(echo "$branch_json" | jq -r '.name')'"

merge_json=$( \
    gitlab new-merge-request \
    "$branch_name" \
    "develop" \
    "WIP: $title" \
    "Closes $issue_number"
)

echo "Created merge request '$(echo "$merge_json" | jq -r '.title')'"

issue_url=$(echo "$issue_json" | jq -r '.web_url')

timer_json=$(harvest start-timing "$title" "$issue_url")

echo "Started timer '$(echo "$timer_json" | jq -r '.notes')'"

git fetch origin

git checkout -b "$branch_name" "origin/$branch_name"
